insert into public.site_image_slots (key, page, section, title, image_url, alt_text, caption, notes, sort_order, is_active)
values
('home.hero.primary', '/', 'hero', 'Homepage hero', '/images/home/hero-primary.jpg', 'Luxury ballroom ready for event draping in Montreal', null, 'Primary homepage hero visual', 0, true),
('home.estimate.promo', '/', 'estimate-promo', 'Estimate promo visual', '/images/home/estimate-promo.jpg', 'Elegant event space illustrating drape rental planning', null, 'Homepage estimate builder promo panel', 0, true),
('home.how_it_works.visual', '/', 'how-it-works', 'How it works visual', '/images/home/how-it-works.jpg', 'Event tables and décor atmosphere for drape planning', null, null, 0, true),
('home.services.wedding', '/', 'services', 'Wedding service card', '/images/services/wedding-card.jpg', 'Elegant wedding draping with candles and fabric backdrop', null, null, 1, true),
('home.services.pipe_drape', '/', 'services', 'Pipe and drape service card', '/images/services/pipe-card.jpg', 'Ballroom interior suited to pipe and drape venue walls', null, null, 2, true),
('home.services.corporate', '/', 'services', 'Corporate service card', '/images/services/corporate-card.jpg', 'Theater stage curtains for corporate event draping', null, null, 3, true),
('home.services.stage', '/', 'services', 'Stage backdrop service card', '/images/services/stage-card.jpg', 'Red velvet stage curtains for backdrop rental', null, null, 4, true),
('home.services.blackout', '/', 'services', 'Blackout service card', '/images/services/blackout-card.jpg', 'Black fabric texture for blackout and masking drapes', null, null, 5, true),
('home.services.mitzvah', '/', 'services', 'Bar Bat Mitzvah service card', '/images/services/mitzvah-card.jpg', 'Celebration stage with drapery for mitzvah events', null, null, 6, true),
('home.gallery.wedding', '/', 'gallery-teaser', 'Gallery teaser wedding', '/images/home/gallery-wedding.jpg', 'Wedding draping inspiration example', null, null, 0, true),
('home.gallery.pipe_drape', '/', 'gallery-teaser', 'Gallery teaser pipe and drape', '/images/home/gallery-pipe.jpg', 'Pipe and drape venue transformation inspiration', null, null, 0, true),
('home.gallery.stage', '/', 'gallery-teaser', 'Gallery teaser stage', '/images/home/gallery-stage.jpg', 'Stage curtain backdrop inspiration', null, null, 0, true),
('home.gallery.corporate', '/', 'gallery-teaser', 'Gallery teaser corporate', '/images/home/gallery-corporate.jpg', 'Corporate event draping inspiration', null, null, 0, true),
('home.gallery.blackout', '/', 'gallery-teaser', 'Gallery teaser blackout', '/images/home/gallery-blackout.jpg', 'Blackout masking fabric inspiration', null, null, 0, true),
('home.gallery.mitzvah', '/', 'gallery-teaser', 'Gallery teaser mitzvah', '/images/home/gallery-mitzvah.jpg', 'Celebration backdrop draping inspiration', null, null, 0, true),
('home.areas.montreal', '/', 'areas', 'Montreal area card', '/images/home/area-montreal.jpg', 'Montreal event venue atmosphere for drape rental', null, null, 0, true),
('home.areas.laval', '/', 'areas', 'Laval area card', '/images/home/area-laval.jpg', 'Laval event venue atmosphere for drape rental', null, null, 0, true),
('home.areas.longueuil', '/', 'areas', 'Longueuil area card', '/images/home/area-longueuil.jpg', 'Longueuil event venue atmosphere for drape rental', null, null, 0, true),
('home.areas.west_island', '/', 'areas', 'West Island area card', '/images/home/area-west-island.jpg', 'West Island celebration draping atmosphere', null, null, 0, true),
('home.cta.atmosphere', '/', 'final-cta', 'Final CTA atmosphere', '/images/cta/atmosphere.jpg', 'Event backdrop atmosphere for estimate CTA', null, null, 0, true),
('services.hub.hero', '/services', 'hero', 'Services hub visual', '/images/services/hub-hero.jpg', 'Luxury event venue suited to drape rental services', null, null, 0, true),
('services.wedding-draping.hero', '/services/wedding-draping', 'hero-aside', 'Wedding draping hero', '/images/services/wedding-hero.jpg', 'Outdoor wedding ceremony with white drapes and florals', null, 'Inspiration example — not a claimed TCG portfolio shot', 0, true),
('services.wedding-draping.aside', '/services/wedding-draping', 'aside', 'Wedding draping aside', '/images/services/wedding-aside.jpg', 'Wedding draping ceremony fabric detail', null, null, 0, true),
('services.wedding-draping.detail', '/services/wedding-draping', 'detail', 'Wedding draping detail', '/images/services/wedding-detail.jpg', 'Wedding reception ambiance with soft event lighting', null, null, 0, true),
('services.pipe-and-drape-rental.hero', '/services/pipe-and-drape-rental', 'hero-aside', 'Pipe and drape hero', '/images/services/pipe-hero.jpg', 'Grand event room illustrating pipe and drape transformation', null, null, 0, true),
('services.pipe-and-drape-rental.aside', '/services/pipe-and-drape-rental', 'aside', 'Pipe and drape aside', '/images/services/pipe-aside.jpg', 'Ballroom perimeter suited to modular drape walls', null, null, 0, true),
('services.pipe-and-drape-rental.detail', '/services/pipe-and-drape-rental', 'detail', 'Pipe and drape detail', '/images/services/pipe-detail.jpg', 'Wedding aisle and venue structure for partition planning', null, null, 0, true),
('services.corporate-event-draping.hero', '/services/corporate-event-draping', 'hero-aside', 'Corporate draping hero', '/images/services/corporate-hero.jpg', 'Stage curtains for corporate presentation draping', null, null, 0, true),
('services.corporate-event-draping.aside', '/services/corporate-event-draping', 'aside', 'Corporate draping aside', '/images/services/corporate-aside.jpg', 'Gala ballroom polish for corporate event draping', null, null, 0, true),
('services.corporate-event-draping.detail', '/services/corporate-event-draping', 'detail', 'Corporate draping detail', '/images/services/corporate-detail.jpg', 'Conference and event atmosphere for corporate draping', null, null, 0, true),
('services.stage-backdrop-rentals.hero', '/services/stage-backdrop-rentals', 'hero-aside', 'Stage backdrop hero', '/images/services/stage-hero.jpg', 'Red velvet stage curtains for backdrop rental', null, null, 0, true),
('services.stage-backdrop-rentals.aside', '/services/stage-backdrop-rentals', 'aside', 'Stage backdrop aside', '/images/services/stage-aside.jpg', 'Vertical stage curtain folds for event backdrops', null, null, 0, true),
('services.stage-backdrop-rentals.detail', '/services/stage-backdrop-rentals', 'detail', 'Stage backdrop detail', '/images/services/stage-detail.jpg', 'Presentation stage setting for backdrop draping', null, null, 0, true),
('services.blackout-room-divider-drapes.hero', '/services/blackout-room-divider-drapes', 'hero-aside', 'Blackout drapes hero', '/images/services/blackout-hero.jpg', 'Opaque black fabric for blackout and masking', null, null, 0, true),
('services.blackout-room-divider-drapes.aside', '/services/blackout-room-divider-drapes', 'aside', 'Blackout drapes aside', '/images/services/blackout-aside.jpg', 'Black fabric texture for room divider drapes', null, null, 0, true),
('services.blackout-room-divider-drapes.detail', '/services/blackout-room-divider-drapes', 'detail', 'Blackout drapes detail', '/images/gallery/blackout/03.jpg', 'Dark textile folds for light-control draping', null, null, 0, true),
('services.bar-bat-mitzvah-draping.hero', '/services/bar-bat-mitzvah-draping', 'hero-aside', 'Mitzvah draping hero', '/images/services/mitzvah-hero.jpg', 'Celebration stage with drapery for Bar or Bat Mitzvah', null, null, 0, true),
('services.bar-bat-mitzvah-draping.aside', '/services/bar-bat-mitzvah-draping', 'aside', 'Mitzvah draping aside', '/images/services/mitzvah-aside.jpg', 'Photo backdrop draping for celebration moments', null, null, 0, true),
('services.bar-bat-mitzvah-draping.detail', '/services/bar-bat-mitzvah-draping', 'detail', 'Mitzvah draping detail', '/images/gallery/mitzvah/02.jpg', 'Festive stage drapery for celebration events', null, null, 0, true),
('areas.montreal.hero', '/areas/montreal', 'hero', 'Montreal area hero', '/images/areas/montreal-hero.jpg', 'Montreal ballroom atmosphere for event drape rentals', null, null, 0, true),
('areas.montreal.atmosphere', '/areas/montreal', 'atmosphere', 'Montreal atmosphere', '/images/areas/montreal-atmosphere.jpg', 'Stage draping atmosphere for Montreal events', null, null, 0, true),
('areas.laval.hero', '/areas/laval', 'hero', 'Laval area hero', '/images/areas/laval-hero.jpg', 'Event venue atmosphere for Laval drape rentals', null, null, 0, true),
('areas.laval.atmosphere', '/areas/laval', 'atmosphere', 'Laval atmosphere', '/images/areas/laval-atmosphere.jpg', 'Celebration draping atmosphere for Laval events', null, null, 0, true),
('areas.longueuil.hero', '/areas/longueuil', 'hero', 'Longueuil area hero', '/images/areas/longueuil-hero.jpg', 'Event room atmosphere for Longueuil drape rentals', null, null, 0, true),
('areas.longueuil.atmosphere', '/areas/longueuil', 'atmosphere', 'Longueuil atmosphere', '/images/areas/longueuil-atmosphere.jpg', 'Backdrop draping atmosphere for South Shore events', null, null, 0, true),
('areas.west-island.hero', '/areas/west-island', 'hero', 'West Island area hero', '/images/areas/west-island-hero.jpg', 'Wedding draping atmosphere for West Island venues', null, null, 0, true),
('areas.west-island.atmosphere', '/areas/west-island', 'atmosphere', 'West Island atmosphere', '/images/areas/west-island-atmosphere.jpg', 'Stage curtain atmosphere for West Island events', null, null, 0, true),
('gallery.wedding.1', '/gallery', 'wedding', 'Gallery wedding 1', '/images/gallery/wedding/01.jpg', 'Wedding draping inspiration with candles and fabric', 'Inspiration example', null, 1, true),
('gallery.wedding.2', '/gallery', 'wedding', 'Gallery wedding 2', '/images/gallery/wedding/02.jpg', 'Celebration stage drapery inspiration', 'Inspiration example', null, 2, true),
('gallery.wedding.3', '/gallery', 'wedding', 'Gallery wedding 3', '/images/gallery/wedding/03.jpg', 'Wedding stage with florals and drapery', 'Inspiration example', null, 3, true),
('gallery.wedding.4', '/gallery', 'wedding', 'Gallery wedding 4', '/images/gallery/wedding/04.jpg', 'Reception tables with elegant event décor', 'Inspiration example', null, 4, true),
('gallery.pipe-and-drape.1', '/gallery', 'pipe-and-drape', 'Gallery pipe and drape 1', '/images/gallery/pipe-and-drape/01.jpg', 'Venue transformation with modular drape walls', 'Inspiration example', null, 1, true),
('gallery.pipe-and-drape.2', '/gallery', 'pipe-and-drape', 'Gallery pipe and drape 2', '/images/gallery/pipe-and-drape/02.jpg', 'Ballroom perimeter for pipe and drape zoning', 'Inspiration example', null, 2, true),
('gallery.stage.1', '/gallery', 'stage', 'Gallery stage 1', '/images/gallery/stage/01.jpg', 'Red velvet stage curtain backdrop', 'Inspiration example', null, 1, true),
('gallery.stage.2', '/gallery', 'stage', 'Gallery stage 2', '/images/gallery/stage/02.jpg', 'Stage curtain folds for event backdrops', 'Inspiration example', null, 2, true),
('gallery.stage.3', '/gallery', 'stage', 'Gallery stage 3', '/images/gallery/stage/03.jpg', 'Stage draping inspiration for presentations', 'Inspiration example', null, 3, true),
('gallery.corporate.1', '/gallery', 'corporate', 'Gallery corporate 1', '/images/gallery/corporate/01.jpg', 'Corporate stage draping inspiration', 'Inspiration example', null, 1, true),
('gallery.corporate.2', '/gallery', 'corporate', 'Gallery corporate 2', '/images/gallery/corporate/02.jpg', 'Gala ballroom draping inspiration', 'Inspiration example', null, 2, true),
('gallery.corporate.3', '/gallery', 'corporate', 'Gallery corporate 3', '/images/gallery/corporate/04.jpg', 'Conference event atmosphere for corporate draping', 'Inspiration example', null, 3, true),
('gallery.blackout.1', '/gallery', 'blackout', 'Gallery blackout 1', '/images/gallery/blackout/01.jpg', 'Black fabric for blackout masking', 'Inspiration example', null, 1, true),
('gallery.blackout.2', '/gallery', 'blackout', 'Gallery blackout 2', '/images/gallery/blackout/02.jpg', 'Dark stage curtains for light control', 'Inspiration example', null, 2, true),
('gallery.blackout.3', '/gallery', 'blackout', 'Gallery blackout 3', '/images/gallery/blackout/03.jpg', 'Opaque textile folds for room masking', 'Inspiration example', null, 3, true),
('gallery.mitzvah.1', '/gallery', 'mitzvah', 'Gallery mitzvah 1', '/images/gallery/mitzvah/01.jpg', 'Photo backdrop draping for celebrations', 'Inspiration example', null, 1, true),
('gallery.mitzvah.2', '/gallery', 'mitzvah', 'Gallery mitzvah 2', '/images/gallery/mitzvah/02.jpg', 'Festive stage drapery for Bar or Bat Mitzvah', 'Inspiration example', null, 2, true),
('gallery.mitzvah.3', '/gallery', 'mitzvah', 'Gallery mitzvah 3', '/images/gallery/mitzvah/04.jpg', 'Celebration décor atmosphere for mitzvah draping', 'Inspiration example', null, 3, true),
('about.primary', '/about', 'primary', 'About primary visual', '/images/about/primary.jpg', 'Historic ballroom suited to full-service event drape rental', null, null, 0, true),
('ai.studio.primary', '/ai', 'primary', 'AI studio visual', '/images/ai/studio-primary.jpg', 'Velvet stage curtains evoking future drape studio visualization', null, null, 0, true),
('estimate.intro', '/get-estimate', 'intro', 'Estimate intro visual', '/images/estimate/intro.jpg', 'Grand ballroom for Montreal event drape estimate planning', null, null, 0, true),
('contact.atmosphere', '/contact', 'atmosphere', 'Contact atmosphere', '/images/contact/atmosphere.jpg', 'Event venue atmosphere when contacting The Curtain Guy', null, null, 0, true)
on conflict (key) do update set
  page = excluded.page,
  section = excluded.section,
  title = excluded.title,
  image_url = excluded.image_url,
  alt_text = excluded.alt_text,
  caption = excluded.caption,
  notes = excluded.notes,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();
